### PR TITLE
[trivial] Fix spelling

### PR DESCRIPTION
**Pull request by vishalsodani**
Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Comment by vishalsodani** [comment]
I have already signed the CLA.

**Comment by koraa** [comment]
Thank you for our contribution! I think you have to close and reopen to get that confirmation…

**Comment by koraa** [comment]
Ah didn't work. Could you try closing and reopening?

**Comment by koraa** [comment]
Are you sure you have signed the CLA?

**Comment by vishalsodani** [comment]
> 
> 
> Are you sure you have signed the CLA?

Yes :) I have even received an email with 2 pdf files.

**Pull request closed without merging**
